[workspace]
channels = ["https://prefix.dev/conda-forge"]
name = "mri-fcd-detection"
platforms = ["linux-64", "win-64"]

[system-requirements]
cuda = "12.0"

[dependencies]
pytorch-gpu = "*"
matplotlib = ">=3.10.1,<4"
monai = ">=1.4.0,<2"
ipykernel = ">=6.29.5,<7"
ipywidgets = ">=8.1.7,<9"
nibabel = ">=5.3.2,<6"
scikit-learn = ">=1.6.1,<2"
seaborn = ">=0.13.2,<0.14"
